# Generated by Django 6.0.5 on 2026-05-13 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Назва')),
                ('bike_type', models.CharField(choices=[('regular', 'Звичайний велосипед'), ('electric', 'Електровелосипед')], default='regular', max_length=10, verbose_name='Тип велосипеда')),
                ('frame', models.CharField(max_length=100, verbose_name='Рама')),
                ('wheels', models.CharField(max_length=100, verbose_name='Колеса')),
                ('brakes', models.CharField(max_length=100, verbose_name='Гальма')),
                ('gears', models.CharField(max_length=100, verbose_name='Передачі')),
                ('color', models.CharField(max_length=60, verbose_name='Колір')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bikes/', verbose_name='Зображення')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('battery_capacity', models.CharField(blank=True, max_length=80, verbose_name='Акумулятор')),
                ('motor_power', models.CharField(blank=True, max_length=80, verbose_name='Мотор')),
                ('range_km', models.PositiveIntegerField(default=0, verbose_name='Запас ходу (км)')),
                ('charge_time', models.CharField(blank=True, max_length=60, verbose_name='Час заряджання')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наявності')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеди',
                'ordering': ['bike_type', 'price'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Загальна вартість')),
                ('status', models.CharField(choices=[('pending', 'Очікує обробки'), ('confirmed', 'Підтверджено'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус')),
                ('delivery_address', models.TextField(verbose_name='Адреса доставки')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.bikemodel', verbose_name='Велосипед')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
    ]
